LANG_EN = "en"
LANG_RU = "ru"

TEXT = {
    "en": {
        "welcome": "Main menu",
        "help": "Commands:\n/start\n/help\n/lang\n/config <id>",
        "lang_set": "Language set to English.",
        "lang_pick": "Choose language:",
        "lang_button_en": "🇬🇧 English",
        "lang_button_ru": "🇷🇺 Русский",
        "menu_configs": "Configs",
        "menu_devices": "My devices",
        "menu_suggest": "Suggest config",
        "menu_admin": "Admin panel",
        "menu_back": "Back",
        "menu_cancel": "Cancel",
        "configs_title": "Configs section",
        "cfg_by_brand": "By brand",
        "cfg_recent": "Recently approved",
        "cfg_list_header": "Configs:",
        "cfg_download_btn": "Download #{id}",
        "empty": "Nothing found.",
        "brands_hint": "Choose a brand:",
        "brand_prev": "< Prev",
        "brand_next": "Next >",
        "brand_empty": "No configs for this brand.",
        "devices_title": "My devices section",
        "dev_add": "Add device",
        "dev_list": "List devices",
        "dev_check": "Check devices",
        "ask_device": "Send device model text.\nBetter with <code>.notch device</code>",
        "device_added": "Device added: {model}",
        "device_exists": "Device already exists: {model}",
        "my_devices_empty": "No saved devices yet.",
        "my_devices_header": "Your devices:",
        "devices_search_header": "Found configs for your devices. Tap to download:",
        "devices_search_item": "{model}: {count}",
        "devices_search_empty": "No configs found for your saved devices.",
        "suggest_send_config": "Send .notch config file first.\nBetter with <code>.notch cfg</code>",
        "suggest_config_received": "Config received.\nSubmission #{id}\nBrand: {brand}\nModel: {model}",
        "choose_visibility": "Show author in published list?",
        "show_author": "Show author",
        "hide_author": "Hide author (anonymous)",
        "send_before": "Send proof of config working (video or screenshot).",
        "proof_required": "Send video or screenshot.",
        "proof_media_limit": "Too many media items. Maximum allowed: {max}.",
        "sent_to_moderation": "Sent to moderation.",
        "approved_user": "Your submission was approved. Published config ID: #{id}",
        "rejected_user": "Your submission #{id} was rejected.",
        "rejected_user_reason": "Your submission #{id} was rejected.\nReason: {reason}",
        "notify_model": "New approved config for your device model: {model}\nID: #{id}",
        "only_notch": "Please send a .notch file.\nBetter with <code>.notch cfg</code>",
        "save_failed": "Failed to save file.",
        "usage_config": "Usage: /config <id>",
        "not_found": "Config not found.",
        "author_hidden": "anonymous",
        "admin_only": "Admins only.",
        "admin_queue_btn": "Queue",
        "admin_refresh_btn": "Refresh",
        "admin_view_btn": "View by ID",
        "admin_approve_btn": "Approve",
        "admin_reject_btn": "Reject",
        "admin_queue_empty": "No pending submissions.",
        "admin_queue_header": "Pending submissions:",
        "admin_not_found": "Submission not found or not pending.",
        "admin_approved": "Submission #{id} approved. Config #{cfg_id} published.",
        "admin_rejected": "Submission #{id} rejected.",
        "admin_reject_reason_prompt": "Send rejection reason for submission #{id}.",
        "admin_reject_reason_empty": "Reason cannot be empty. Send text reason.",
        "admin_view_text": "Submission #{id}\nStatus: {status}\nBrand: {brand}\nModel: {model}\nMode: {mode_id}\nAuthor: {author}\nAnonymous: {anon}",
        "admin_proof": "Proof",
    },
    "ru": {
        "welcome": "Главное меню",
        "help": "Команды:\n/start\n/help\n/lang\n/config <id>",
        "lang_set": "Язык переключен на русский.",
        "lang_pick": "Выбери язык:",
        "lang_button_en": "🇬🇧 English",
        "lang_button_ru": "🇷🇺 Русский",
        "menu_configs": "Конфиги",
        "menu_devices": "Мои устройства",
        "menu_suggest": "Предложить конфиг",
        "menu_admin": "Админ-панель",
        "menu_back": "Назад",
        "menu_cancel": "Отмена",
        "configs_title": "Раздел конфигов",
        "cfg_by_brand": "По бренду",
        "cfg_recent": "Недавно одобренные",
        "cfg_list_header": "Конфиги:",
        "cfg_download_btn": "Скачать #{id}",
        "empty": "Ничего не найдено.",
        "brands_hint": "Выбери бренд:",
        "brand_prev": "< Назад",
        "brand_next": "Далее >",
        "brand_empty": "Для этого бренда конфигов нет.",
        "devices_title": "Раздел моих устройств",
        "dev_add": "Добавить устройство",
        "dev_list": "Список устройств",
        "dev_check": "Проверить устройства",
        "ask_device": "Отправь модель устройства текстом.\nЛучше через <code>.notch device</code>",
        "device_added": "Устройство добавлено: {model}",
        "device_exists": "Устройство уже есть: {model}",
        "my_devices_empty": "Список устройств пуст.",
        "my_devices_header": "Твои устройства:",
        "devices_search_header": "Найдены конфиги для твоих устройств. Нажми, чтобы скачать:",
        "devices_search_item": "{model}: {count}",
        "devices_search_empty": "Для твоих устройств конфиги не найдены.",
        "suggest_send_config": "Сначала отправь файл .notch.\nМожешь через <code>.notch cfg</code>",
        "suggest_config_received": "Конфиг получен.\nЗаявка #{id}\nБренд: {brand}\nМодель: {model}",
        "choose_visibility": "Показывать твой юзернейм в списке конфигов?",
        "show_author": "Показывать автора",
        "hide_author": "Скрыть автора (анонимно)",
        "send_before": "Отправь подтверждение работы конфига (видео или скрин).",
        "proof_required": "Отправь видео или скрин.",
        "proof_media_limit": "Слишком много медиа. Максимум: {max}.",
        "sent_to_moderation": "Отправлено на модерацию.",
        "approved_user": "Твоя заявка одобрена. Опубликованный конфиг ID: #{id}",
        "rejected_user": "Твоя заявка #{id} отклонена.",
        "rejected_user_reason": "Твоя заявка #{id} отклонена.\nПричина: {reason}",
        "notify_model": "Новый одобренный конфиг для твоей модели: {model}\nID: #{id}",
        "only_notch": "Отправь файл с расширением .notch.\nНапомню, через <code>.notch cfg</code>",
        "save_failed": "Не удалось сохранить файл.",
        "usage_config": "Использование: /config <id>",
        "not_found": "Конфиг не найден.",
        "author_hidden": "аноним",
        "admin_only": "Только для админов.",
        "admin_queue_btn": "Очередь",
        "admin_refresh_btn": "Обновить",
        "admin_view_btn": "Просмотр",
        "admin_approve_btn": "Одобрить",
        "admin_reject_btn": "Отклонить",
        "admin_queue_empty": "Нет заявок на модерацию.",
        "admin_queue_header": "Заявки в ожидании:",
        "admin_not_found": "Заявка не найдена или уже обработана.",
        "admin_approved": "Заявка #{id} одобрена. Конфиг #{cfg_id} опубликован.",
        "admin_rejected": "Заявка #{id} отклонена.",
        "admin_reject_reason_prompt": "Отправь причину отказа для заявки #{id}.",
        "admin_reject_reason_empty": "Причина не может быть пустой. Отправь текст.",
        "admin_view_text": "Заявка #{id}\nСтатус: {status}\nБренд: {brand}\nМодель: {model}\nРежим: {mode_id}\nАвтор: {author}\nАнонимно: {anon}",
        "admin_proof": "Подтверждение",
    },
}

def t(lang: str, key: str, **kwargs) -> str:
    base = TEXT[lang if lang in TEXT else LANG_EN][key]
    return base.format(**kwargs)
